### ISSUE TITLE
list index out of range when getting authenticated user

### ISSUE THREAD

**Issue by fitzthum** [costastf/locationsharinglib#65] opened 2019-07-29 03:40 UTC
Service.get_authenticated_user() is returning None for me. When I dig a little, it turns out that [line 165](https://github.com/costastf/locationsharinglib/blob/master/locationsharinglib/locationsharinglib.py#L165) is catching an IndexError from the [line 146](https://github.com/costastf/locationsharinglib/blob/master/locationsharinglib/locationsharinglib.py#L146). When I print out the output returned from _get_data(), it only has length 9. Not really sure what is going on here. Seems like I am not getting enough data back from Google?

**Comment by costastf** [comment] 2019-07-29 06:42
Yeah, afraid so. This feature is in because some people actually use their own accounts to share stuff to so they want to get their own info as well. I don't think that's a great idea personally and if you use a generic account then there is no info to return so in that sense the authenticated user has no info. That's is how I have set things up myself.

**Comment by costastf** [comment] 2019-07-29 06:42
Not a bug so closing.

**Closed as completed by costastf** 2019-07-29 06:43 UTC

**Comment by fitzthum** [comment] 2019-07-29 08:47
I am not using a generic account. My goal is to get the data from my own account. I want to track the location of my phone, which is paired to my account. Perhaps I am not sharing the location correctly. The location sharing settings on the maps app will not let you explicitly share the data with your own account. I had assumed that since Google will give me info on my phone via a web search, the get_authenticated_user() method would return the same info about my phone. Is there some additional configuration that needs to be done?

**Comment by costastf** [comment] 2019-07-29 08:59
I am not sure and i have the hunch that it is also locale specific. I have
had reports for google responding differently depending on location. The
easiest and most straight forward way I  suggest is to setup a new sharing
account and share the locations of all people you are interested in with
that. That way your personal account is fully featured as shared and you
don't care about the generic on not showing details.

**Comment by fitzthum** [comment] 2019-07-29 09:09
yeah it works fine using a second account. this does seem like a bug, though. i guess it isn't particularly important.
